import React from 'react'

export default function RecommendationCard({ rec, index }) {
  const getImpactColor = (impact) => {
    switch(impact?.toLowerCase()) {
      case 'critical': return '#ef4444' // red
      case 'high':     return '#f59e0b' // amber
      case 'medium':   return '#3b82f6' // blue
      default:         return '#22c55e' // green
    }
  }
  const color = getImpactColor(rec.impact)

  return (
    <div
      className="glass-card fade-in"
      style={{
        padding: '24px',
        animationDelay: `${index * 0.1}s`,
        display: 'flex',
        flexDirection: 'column',
        gap: 16,
        borderLeft: `4px solid ${color}`,
        position: 'relative',
        overflow: 'hidden'
      }}
    >
      {/* Background glow */}
      <div style={{
        position: 'absolute', top: -40, right: -40, width: 120, height: 120,
        background: `radial-gradient(circle, ${color}30 0%, transparent 70%)`,
        zIndex: 0, pointerEvents: 'none'
      }} />

      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', zIndex: 1 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{
            width: 44, height: 44,
            borderRadius: 12,
            background: `${color}15`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '1.4rem'
          }}>
            {rec.icon || '💡'}
          </div>
          <div>
            <div style={{ fontSize: '0.75rem', fontWeight: 700, color: color, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              {rec.type || 'Recommendation'}
            </div>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-primary)', marginTop: 2 }}>
              {rec.title}
            </h3>
          </div>
        </div>
        
        <div style={{
          padding: '4px 10px',
          borderRadius: 99,
          background: `${color}20`,
          color: color,
          fontSize: '0.7rem',
          fontWeight: 700,
          textTransform: 'uppercase',
          letterSpacing: '0.05em'
        }}>
          {rec.impact} Impact
        </div>
      </div>

      <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.6, zIndex: 1 }}>
        {rec.description}
      </div>
      
      <div style={{ marginTop: 'auto', paddingTop: 16, borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', zIndex: 1 }}>
        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Auto-generated by AI Intelligence Engine</span>
        <button style={{
          background: 'none', border: 'none', color: 'var(--accent)', fontSize: '0.8rem', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4
        }}>
          Take Action <span>→</span>
        </button>
      </div>
    </div>
  )
}
